[project]
name = "otakudb"
version = "0.3.0"
dependencies = [
	"questionary",
	"dulwich>=1.2.6",
	"dublib==0.31.0"
]

[project.optional-dependencies]
dev = ["ruff", "ty"]

[tool.ruff.lint]
select = ["A", "ARG", "C", "E", "F", "I", "N818"]
ignore = ["E701", "E501"]

[tool.ruff.lint.isort]
lines-after-imports = 1
sections = {"dublib" = ["dublib"]}
section-order = [
	"future",
	"standard-library",
	"third-party",
	"dublib",
	"first-party",
	"local-folder"
]